# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/gvolpe/nix-index-database/releases/download/2025-08-17-031846/index-";
  hashes = {
    x86_64-linux = "sha256-MDrO/WeLL/PVo/yJXCT+Syo5Za4VvH2MNpCBSZOEbTg=";
    aarch64-linux = "sha256-HtxM2Laui0Namh1fLntdP92jZ0wedKidECAwxL4rjUk=";
    x86_64-darwin = "sha256-EPG9hXo01Rkd6FD9EdgZlkRtCNZTpEb7Ujtw90ZiCmA=";
    aarch64-darwin = "sha256-tiRwusWt7XeGAIdd0+hSzWJyMUqtndvw2i+Xxh74u1o=";
    x86_64-linux-small = "sha256-uiSoRzSVGN5togpDiUXj5xPOngwKlBmHrO9LKD8aw9M=";
    aarch64-linux-small = "sha256-pHLtmk+M8O6WjeaipSwUVW5omvuw7hPFYKecDZpe/J0=";
    x86_64-darwin-small = "sha256-o79dvK06gFlQ8aX1qlWJFvz6T4ss5DqYDLQ47TJ/2G8=";
    aarch64-darwin-small = "sha256-ukAb3yPfYa9MHfmTFPpDPGvayheK08IN2pnv4JmRMIw=";
  };
}
