# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/gvolpe/nix-index-database/releases/download/2026-03-01-034520/index-";
  hashes = {
    x86_64-linux = "sha256-+ZmJrHV8EcSk4IjoPYpxL8J6iTOsHac0ULZS5OOkHGY=";
    aarch64-linux = "sha256-y7LM9lWJGEJ5Holvi1L2zwsU2OVquNMUf/DJCRkyLuU=";
    x86_64-darwin = "sha256-7aWztJGvpkJuY8IUrSys3urn6NF9pAbqtES+ooEXZFU=";
    aarch64-darwin = "sha256-iQZgthqrVpF2PwKE3enrOfw823hXpTfWHdUtJVOOjjo=";
    x86_64-linux-small = "sha256-nd5+EIKnC1bxZyVndesj6Y6WnjLHcUQjaDARkEZyUog=";
    aarch64-linux-small = "sha256-NMgTwVlDRYz9X+s46cS3yhqAbiB3Z/ffQrAdrwaeAj4=";
    x86_64-darwin-small = "sha256-YOxr+yH0F7hLqqKP8UdxHnT5hiMtCyr75TyiSYghYvc=";
    aarch64-darwin-small = "sha256-qUgxzWH8tpxQ1BboNywopn7LF6lTGddHS7FweCB6Mdc=";
  };
}
