# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/gvolpe/nix-index-database/releases/download/2025-03-09-025307/index-";
  hashes = {
    x86_64-linux = "sha256-t1KeISX+Hv7sLV+uAL/k0SXw2SB1CQmCDdCVhHkR9io=";
    aarch64-linux = "sha256-4T5n+ssCanmuKE0J6p/TddVDg3+TVKJQoK/65bQzhGk=";
    x86_64-darwin = "sha256-2zykuB3my4psrSoqFRdjQnDo8GReviedKhmfKM+fVzY=";
    aarch64-darwin = "sha256-r3Yyq81j0KR9yr+h3x4X2jKzoDrvUm9vyEHmzcax4W0=";
    x86_64-linux-small = "sha256-kCp8+Ra5csZx3hm3sfJ6NUAggi9/04WCTKtX2KCBycc=";
    aarch64-linux-small = "sha256-hcD8QNd4aBGIVYHGUVAuuKlhTdoP1lGXNC0l+C+ybOw=";
    x86_64-darwin-small = "sha256-Wbgz5qXIZbVjIqsd6Gt9dzHMRoIYYx5B3qspn/DGcR4=";
    aarch64-darwin-small = "sha256-8ml+Yo5T3F469HocgKRy5u/NfCqoQryGsZEfzVHIn98=";
  };
}
